services:
  db:
    image: postgres:16
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:16
    ports:
      - ${TEST_DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_HOST=${TEST_DB_HOST}

  api:
    container_name: api
    build:
      context: .
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "8011:8000"
    depends_on:
      db:
        condition: service_healthy
