"""Add index to string column

Revision ID: 739e35d68c46
Revises: c2f355da3bf6
Create Date: 2025-02-06 16:32:33.545783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739e35d68c46'
down_revision = 'c2f355da3bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('string_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_string_model_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('string_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_string_model_value'))

    # ### end Alembic commands ###
